DROP TABLE IF EXISTS listings;

CREATE TABLE listings (
  id SERIAL PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  city VARCHAR(80) NOT NULL,
  price INTEGER NOT NULL CHECK (price > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'available',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
